### ISSUE TITLE
Building queryservice fails (missing dependency for protobuf)

### ISSUE THREAD

**Issue by pbavinck** [kbhattac/coolretailer#2]
STEPS TO REPRODUCE
- create new project
- set project to newly created project (gcloud)
- Confirm project (tutorial)
- Enable API's (tutorial)
- launch deploy.sh
#service account creation OK
#policy binding OK
#importing data

--2019-03-07 11:35:12--  https://raw.githubusercontent.com/BestBuyAPIs/open-data-set/master/products.json
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 39685207 (38M) [text/plain]
Saving to: ‘products.json.1’

products.json.1                           100%[=====================================================================================>]  37.85M   210MB/s    in 0.2s

2019-03-07 11:35:13 (210 MB/s) - ‘products.json.1’ saved [39685207/39685207]

[INFO] Scanning for projects...
[INFO]
[INFO] -------------------< com.coolretailer:queryservice >--------------------
[INFO] Building queryservice 1.0.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] >>> spring-boot-maven-plugin:2.1.1.RELEASE:run (default-cli) > test-compile @ queryservice >>>
[WARNING] The POM for com.coolretailer:protobuf:jar:1.0.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.559 s
[INFO] Finished at: 2019-03-07T11:35:22+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project queryservice: Could not resolve dependencies for project com.coolretailer:queryservice:jar:1.0.0: Failure to find com.coolretailer:protobuf:jar:1.0.0 in https://repo.spring.io/milestone was cached in the local repository, resolution will not be reattempted until the update interval of spring-milestones has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
Creating gs://coolretailer-gcs-bucket-kxysj3jrh327pliqnbe4-1551953559/...
ServiceException: 409 Bucket coolretailer-gcs-bucket-kxysj3jrh327pliqnbe4-1551953559 already exists.
CommandException: No URLs matched: products.nd.json
Dataset 'cool-retailer-plb02:coolretailer' successfully created.
BigQuery error in load operation: Error processing job 'cool-retailer-plb02:bqjob_r396448bec35229f3_0000016957b8f485_1': An internal error occurred and the request
could not be completed. Error: 9724253
Failure details:
- An internal error occurred and the request could not be completed.
Error: 9724253
.  Creating cluster... 
WARNING: Starting in 1.12, new clusters will not have a client certificate issued. You can manually enable (or disable) the issuance of the client certificate using the `--[no-]issue-client-certificate` flag.
WARNING: Starting in 1.12, default node pools in new clusters will have their legacy Compute Engine instance metadata endpoints disabled by default. To create a cluster with legacy instance metadata endpoints disabled in the default node pool, run `clusters create` with the flag `--metadata disable-legacy-endpoints=true`.
This will enable the autorepair feature for nodes. Please see https://cloud.google.com/kubernetes-engine/docs/node-auto-repair for more information on node autorepairs.
This will enable the autoupgrade feature for nodes. Please see https://cloud.google.com/kubernetes-engine/docs/node-management for more information on node autoupgrades.
ERROR: (gcloud.beta.container.clusters.create) ResponseError: code=400, message=Master version "1.10.11-gke.1" is unsupported.
Fetching cluster endpoint and auth data.
ERROR: (gcloud.container.clusters.get-credentials) ResponseError: code=404, message=Not found: projects/cool-retailer-plb02/zones/europe-west4-a/clusters/coolretailer.
No cluster named 'coolretailer' in cool-retailer-plb02.

**Comment by kbhattac** [comment]
Fixed. Please check @pbavinck
